# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gRPC_pb2 as gRPC__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gRPC_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhonebookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddContact = channel.unary_unary(
                '/phonebook.Phonebook/AddContact',
                request_serializer=gRPC__pb2.Contact.SerializeToString,
                response_deserializer=gRPC__pb2.Response.FromString,
                _registered_method=True)
        self.GetContact = channel.unary_unary(
                '/phonebook.Phonebook/GetContact',
                request_serializer=gRPC__pb2.Name.SerializeToString,
                response_deserializer=gRPC__pb2.Contact.FromString,
                _registered_method=True)
        self.DeleteContact = channel.unary_unary(
                '/phonebook.Phonebook/DeleteContact',
                request_serializer=gRPC__pb2.Name.SerializeToString,
                response_deserializer=gRPC__pb2.Response.FromString,
                _registered_method=True)
        self.ListContacts = channel.unary_unary(
                '/phonebook.Phonebook/ListContacts',
                request_serializer=gRPC__pb2.Empty.SerializeToString,
                response_deserializer=gRPC__pb2.ContactList.FromString,
                _registered_method=True)


class PhonebookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhonebookServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContact,
                    request_deserializer=gRPC__pb2.Contact.FromString,
                    response_serializer=gRPC__pb2.Response.SerializeToString,
            ),
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=gRPC__pb2.Name.FromString,
                    response_serializer=gRPC__pb2.Contact.SerializeToString,
            ),
            'DeleteContact': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteContact,
                    request_deserializer=gRPC__pb2.Name.FromString,
                    response_serializer=gRPC__pb2.Response.SerializeToString,
            ),
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=gRPC__pb2.Empty.FromString,
                    response_serializer=gRPC__pb2.ContactList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phonebook.Phonebook', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phonebook.Phonebook', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Phonebook(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/AddContact',
            gRPC__pb2.Contact.SerializeToString,
            gRPC__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/GetContact',
            gRPC__pb2.Name.SerializeToString,
            gRPC__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/DeleteContact',
            gRPC__pb2.Name.SerializeToString,
            gRPC__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/ListContacts',
            gRPC__pb2.Empty.SerializeToString,
            gRPC__pb2.ContactList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
