# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gRPC.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gRPC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngRPC.proto\x12\tphonebook\"\'\n\x07\x43ontact\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0b\x43ontactList\x12$\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x12.phonebook.Contact\"\x07\n\x05\x45mpty2\xe6\x01\n\tPhonebook\x12\x35\n\nAddContact\x12\x12.phonebook.Contact\x1a\x13.phonebook.Response\x12\x31\n\nGetContact\x12\x0f.phonebook.Name\x1a\x12.phonebook.Contact\x12\x35\n\rDeleteContact\x12\x0f.phonebook.Name\x1a\x13.phonebook.Response\x12\x38\n\x0cListContacts\x12\x10.phonebook.Empty\x1a\x16.phonebook.ContactListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTACT']._serialized_start=25
  _globals['_CONTACT']._serialized_end=64
  _globals['_NAME']._serialized_start=66
  _globals['_NAME']._serialized_end=86
  _globals['_RESPONSE']._serialized_start=88
  _globals['_RESPONSE']._serialized_end=131
  _globals['_CONTACTLIST']._serialized_start=133
  _globals['_CONTACTLIST']._serialized_end=184
  _globals['_EMPTY']._serialized_start=186
  _globals['_EMPTY']._serialized_end=193
  _globals['_PHONEBOOK']._serialized_start=196
  _globals['_PHONEBOOK']._serialized_end=426
# @@protoc_insertion_point(module_scope)
